# FOG Compute - Betanet Mixnode Services
# Extends base configuration with Betanet mixnode network
# Usage: docker-compose -f docker-compose.yml -f docker-compose.betanet.yml up
#
# NOTE: This configuration SHARES the unified monitoring stack (Prometheus, Grafana, Loki)
#       from the base configuration. No duplicate services!

version: '3.8'

services:
  # Betanet Mixnode 1 (Entry Node)
  betanet-mixnode-1:
    build:
      context: .
      dockerfile: Dockerfile.betanet
    container_name: betanet-mixnode-1
    ports:
      - "9001:9001"  # External port for mixnode communication
    environment:
      NODE_TYPE: entry
      NODE_PORT: 9001
      RUST_LOG: info
      PIPELINE_WORKERS: 4
      BATCH_SIZE: 128
      POOL_SIZE: 1024
      MAX_QUEUE_DEPTH: 10000
      TARGET_THROUGHPUT: 25000
      # Database connection via multi-network bridge
      DATABASE_URL: postgresql://fog_user:fog_password@postgres:5432/fog_compute
    networks:
      - betanet-network  # Primary network for mixnode communication
      - fog-network      # Secondary network for database/backend access
    volumes:
      - ./config/betanet-1:/config
      - ./data/betanet-1:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy
      backend:
        condition: service_healthy

  # Betanet Mixnode 2 (Middle Node)
  betanet-mixnode-2:
    build:
      context: .
      dockerfile: Dockerfile.betanet
    container_name: betanet-mixnode-2
    ports:
      - "9002:9002"
    environment:
      NODE_TYPE: middle
      NODE_PORT: 9002
      RUST_LOG: info
      PIPELINE_WORKERS: 4
      BATCH_SIZE: 128
      POOL_SIZE: 1024
      MAX_QUEUE_DEPTH: 10000
      TARGET_THROUGHPUT: 25000
      DATABASE_URL: postgresql://fog_user:fog_password@postgres:5432/fog_compute
    networks:
      - betanet-network
      - fog-network
    volumes:
      - ./config/betanet-2:/config
      - ./data/betanet-2:/data
    restart: unless-stopped
    depends_on:
      betanet-mixnode-1:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Betanet Mixnode 3 (Exit Node)
  betanet-mixnode-3:
    build:
      context: .
      dockerfile: Dockerfile.betanet
    container_name: betanet-mixnode-3
    ports:
      - "9003:9003"
    environment:
      NODE_TYPE: exit
      NODE_PORT: 9003
      RUST_LOG: info
      PIPELINE_WORKERS: 4
      BATCH_SIZE: 128
      POOL_SIZE: 1024
      MAX_QUEUE_DEPTH: 10000
      TARGET_THROUGHPUT: 25000
      DATABASE_URL: postgresql://fog_user:fog_password@postgres:5432/fog_compute
    networks:
      - betanet-network
      - fog-network
    volumes:
      - ./config/betanet-3:/config
      - ./data/betanet-3:/data
    restart: unless-stopped
    depends_on:
      betanet-mixnode-2:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# No additional volumes needed - using base configuration volumes

# No additional networks needed - using base configuration networks
# betanet-network and fog-network are created in base docker-compose.yml
