version: '3.8'

services:
  # PostgreSQL database for testing
  test-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fog_compute_test
      POSTGRES_USER: fog_test
      POSTGRES_PASSWORD: fog_test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fog_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fog-test-network

  # Redis for caching tests
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - test-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - fog-test-network

  # Fast API backend for integration tests
  test-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://fog_test:fog_test_password@test-postgres:5432/fog_compute_test
      - REDIS_URL=redis://test-redis:6379/0
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - BETANET_URL=http://localhost:9000
      - ENVIRONMENT=test
    ports:
      - "8001:8000"
    depends_on:
      test-postgres:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    networks:
      - fog-test-network
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  test-postgres-data:
  test-redis-data:

networks:
  fog-test-network:
    driver: bridge
