# FOG Compute - Development Overrides
# Extends base docker-compose.yml with development-specific configurations
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # PostgreSQL - Development Overrides
  postgres:
    environment:
      POSTGRES_DB: fog_compute_dev
    ports:
      - "5432:5432"  # Expose for local development tools
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # Backend - Development Overrides
  backend:
    build:
      target: development  # Use development build stage
    environment:
      DATABASE_URL: postgresql+asyncpg://fog_user:fog_password@postgres:5432/fog_compute_dev
      LOG_LEVEL: DEBUG
      RELOAD: "true"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"  # Expose for local development
    volumes:
      # Hot-reload volumes
      - ./backend:/app/backend
      - ./src:/app/src
      - backend_venv:/app/.venv
    command: >
      sh -c "pip install -e /app/backend &&
             python -m uvicorn server.main:app
             --host 0.0.0.0
             --port 8000
             --reload
             --log-level debug"

  # Frontend - Development Overrides
  frontend:
    build:
      dockerfile: Dockerfile.dev  # Use development Dockerfile
      target: development
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000  # Local development URL
      NEXT_TELEMETRY_DISABLED: 1
      WATCHPACK_POLLING: true  # For hot-reload in Docker
    ports:
      - "3000:3000"  # Expose for local development
    volumes:
      # Hot-reload volumes
      - ./apps/control-panel:/app
      - control_panel_modules:/app/node_modules
      - control_panel_next:/app/.next
    command: npm run dev

  # Redis - Development Overrides
  redis:
    ports:
      - "6379:6379"  # Expose for local development tools
    command: redis-server --save 60 1 --loglevel verbose

  # Prometheus - Development Overrides
  prometheus:
    ports:
      - "9090:9090"  # Expose for local access
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'  # Shorter retention for dev
      - '--log.level=debug'

  # Grafana - Development Overrides
  grafana:
    ports:
      - "3001:3000"  # Expose for local access
    environment:
      GF_LOG_LEVEL: debug
      GF_LOG_CONSOLE_LEVEL: debug
      GF_SERVER_ROUTER_LOGGING: true

  # Loki - Development Overrides
  loki:
    ports:
      - "3100:3100"  # Expose for local access

volumes:
  postgres_dev_data:
    driver: local
  backend_venv:
    driver: local
  control_panel_modules:
    driver: local
  control_panel_next:
    driver: local
