from backend.server.constants import ONE_DAY, ONE_GB, ONE_HOUR, ONE_MB, ONE_MINUTE

FIVE_MB = ONE_MB * 5
TEN_MB = ONE_MB * 10

TEST_SMALL_FILE_SIZE = ONE_MB
TEST_MEDIUM_FILE_SIZE = FIVE_MB
TEST_LARGE_FILE_SIZE = TEN_MB
TEST_MAX_FILE_SIZE = ONE_GB
TEST_TIMEOUT_SHORT = 5
TEST_TIMEOUT_MEDIUM = 30
TEST_TIMEOUT_LONG = 120
TEST_USER_EMAIL = "test@example.com"
TEST_USER_PASSWORD = "TestPassword123!"
TEST_PORT = 8000
TEST_HOST = "127.0.0.1"
TEST_PAGE_SIZE = 10
TEST_MAX_LOGIN_ATTEMPTS = 5
TEST_LOCKOUT_DURATION = 300
