"""
Shared constants used across backend test modules.

Decouples tests from scattered literals to improve readability and ease of
updates when requirements change.
"""
from backend.server.constants import (
    ONE_MB,
    TWO_MB,
    THREE_MB,
    FIVE_MB,
    TEN_MB,
    ONE_GB,
    ONE_MINUTE,
    ONE_HOUR,
    ONE_DAY,
    ONE_MONTH,
)

# File sizes (re-exported for convenience)
TEST_SMALL_FILE_SIZE = ONE_MB
TEST_MEDIUM_FILE_SIZE = FIVE_MB
TEST_LARGE_FILE_SIZE = TEN_MB
TEST_MAX_FILE_SIZE = ONE_GB
TEST_FILE_CONTENT = b"x" * 1024
TEST_CHUNK_SIZE = ONE_MB  # Standard chunk size for file transfers

# Timeouts
TEST_TIMEOUT_SHORT = 5
TEST_TIMEOUT_MEDIUM = 30
TEST_TIMEOUT_LONG = 120

# User credentials
TEST_USER_EMAIL = "testuser@example.com"
TEST_USER_PASSWORD = "TestUserPass123!"
TEST_ADMIN_EMAIL = "admin@example.com"

# Network targets
TEST_PORT = 8000
TEST_HOST = "127.0.0.1"
TEST_BASE_URL = f"http://{TEST_HOST}:{TEST_PORT}"

# Pagination and limits
TEST_PAGE_SIZE = 10
TEST_MAX_RESULTS = 100

# Security thresholds
TEST_MAX_LOGIN_ATTEMPTS = 5
TEST_LOCKOUT_DURATION = 300
TEST_TOKEN_LENGTH = 32

# WebSocket testing
TEST_CONNECTIONS_SMALL = 10
TEST_CONNECTIONS_MEDIUM = 50
TEST_CONNECTIONS_LARGE = 100
TEST_ROOM_NAME = "test-room"
TEST_CONNECTION_ID_PREFIX = "test-connection"
TEST_LOAD_CONNECTION_PREFIX = "load-test"
TEST_ROOM_CONNECTIONS = 3
TEST_BROADCAST_CONNECTIONS = 5
TEST_PUBLISHER_COUNT = 6
TEST_MIN_MESSAGE_COUNT = 2
TEST_WINDOW_SECONDS = 60
TEST_MAX_WINDOW_POINTS = 10

# Async timing
TEST_SLEEP_SHORT = 0.05
TEST_SLEEP_MEDIUM = 0.1
TEST_SLEEP_LONG = 0.5

# Account lockout testing
TEST_LOCKOUT_DURATION_MINUTES = 30
TEST_LOCKOUT_DURATION_VARIANCE = 2
TEST_FAILED_ATTEMPTS_BEFORE_LOCK = 3
TEST_NONEXISTENT_USER_ATTEMPTS = 10
TEST_RATE_LIMIT_ATTEMPTS = 20

# Token testing
TEST_ACCESS_TOKEN_EXPIRY_MINUTES = 15
TEST_REFRESH_TOKEN_EXPIRY_DAYS = 7
TEST_MIN_TOKEN_LENGTH = 20
TEST_SIX_DAYS_SECONDS = 6 * 24 * 3600
TEST_REFRESH_RATE_LIMIT_ATTEMPTS = 10

# HTTP status codes for assertions
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_LOCKED = 423
HTTP_TOO_MANY_REQUESTS = 429
HTTP_NOT_IMPLEMENTED = 501

# Test user credentials templates
TEST_USER_PREFIX = "test_user"
TEST_LOCKOUT_USER_PREFIX = "lockout_user"
TEST_REFRESH_USER_PREFIX = "refresh_user"
TEST_DOMAIN = "example.com"
