"""Shared constants for backend services.

This module centralizes configuration-style numeric values to avoid
magic numbers spread throughout the service layer.
"""

# Betanet service constants
BETANET_DEPLOYMENT_DELAY_SECONDS = 5
BETANET_CONNECTIONS_PER_NODE = 3
BETANET_DEFAULT_AVG_LATENCY_MS = 45.0
BETANET_TOTAL_PACKETS_INITIAL = 22274
BETANET_PRIMARY_NODE_PACKETS_PROCESSED = 12453
BETANET_SECONDARY_NODE_PACKETS_PROCESSED = 9821
BETANET_PRIMARY_NODE_UPTIME_SECONDS = 86400
BETANET_SECONDARY_NODE_UPTIME_SECONDS = 72000


# Resource monitor constants
RESOURCE_MONITOR_CPU_PERCENT_INTERVAL = 0.1
RESOURCE_MONITOR_TREND_WINDOW_SIZE = 60
RESOURCE_MONITOR_MIN_TREND_SAMPLES = 10
RESOURCE_MONITOR_TREND_DIFF_THRESHOLD = 5
RESOURCE_MONITOR_CAPACITY_ALERT_THRESHOLD = 70
RESOURCE_MONITOR_CAPACITY_MONITOR_THRESHOLD = 50
RESOURCE_MONITOR_DEFAULT_INTERVAL_SECONDS = 5.0
RESOURCE_MONITOR_HISTORY_MAX_LEN = 1000
RESOURCE_MONITOR_ALERT_HISTORY_MAX_LEN = 100
RESOURCE_MONITOR_CPU_WARNING_PERCENT = 80.0
RESOURCE_MONITOR_CPU_CRITICAL_PERCENT = 95.0
RESOURCE_MONITOR_MEMORY_WARNING_PERCENT = 85.0
RESOURCE_MONITOR_MEMORY_CRITICAL_PERCENT = 95.0
RESOURCE_MONITOR_DISK_WARNING_PERCENT = 85.0
RESOURCE_MONITOR_DISK_CRITICAL_PERCENT = 95.0
RESOURCE_MONITOR_NETWORK_WARNING_PERCENT = 80.0
RESOURCE_MONITOR_NETWORK_CRITICAL_PERCENT = 95.0
RESOURCE_MONITOR_STOP_GRACE_SECONDS = 1.0
RESOURCE_MONITOR_HISTORY_SECONDS_DEFAULT = 60
RESOURCE_MONITOR_RECENT_ALERTS_DEFAULT = 10


# Memory profiler constants
MEMORY_PROFILER_DEFAULT_SNAPSHOT_INTERVAL = 60.0
MEMORY_PROFILER_TRACEMALLOC_TOP_STATS = 10
MEMORY_PROFILER_TOP_OBJECTS_COUNT = 20
MEMORY_PROFILER_SNAPSHOT_HISTORY_MAX_LEN = 1000
MEMORY_PROFILER_MIN_SNAPSHOTS_FOR_LEAK_CHECK = 5
MEMORY_PROFILER_RECENT_SNAPSHOTS_FOR_LEAK = 10
MEMORY_PROFILER_MIN_SNAPSHOTS_FOR_DETECTION = 3
MEMORY_PROFILER_HEAP_WARNING_PERCENT = 80.0
MEMORY_PROFILER_HEAP_CRITICAL_PERCENT = 90.0
MEMORY_PROFILER_GROWTH_RATE_WARNING_PERCENT = 10.0
MEMORY_PROFILER_GC_SPIKE_THRESHOLD_MULTIPLIER = 2.0
MEMORY_PROFILER_LEAK_GROWTH_PERCENT_THRESHOLD = 50
MEMORY_PROFILER_LEAK_GROWTH_COUNT_THRESHOLD = 100
MEMORY_PROFILER_LEAK_SEVERITY_CRITICAL_PERCENT = 200
MEMORY_PROFILER_LEAK_SEVERITY_HIGH_PERCENT = 150
MEMORY_PROFILER_LEAK_SEVERITY_MEDIUM_PERCENT = 100
MEMORY_PROFILER_BASELINE_HEAP_DRIFT_PERCENT_THRESHOLD = 20
MEMORY_PROFILER_BASELINE_OBJECT_DRIFT_PERCENT_THRESHOLD = 30
MEMORY_PROFILER_BASELINE_GC_FREQUENCY_THRESHOLD = 10
MEMORY_PROFILER_GROWTH_RATE_WINDOW_HOURS = 1


# Scheduler constants
SCHEDULER_QUEUE_WAIT_TIMEOUT_SECONDS = 1.0
SCHEDULER_WORKER_ERROR_SLEEP_SECONDS = 1.0
SCHEDULER_DEFAULT_STORAGE_GB = 10
