"""
Shared constants for the backend server.

This module centralizes commonly used values to avoid magic numbers and make
unit conversions explicit across the codebase.
"""

# File size constants
ONE_KB = 1024
ONE_MB = ONE_KB * 1024
FIVE_MB = ONE_MB * 5
TEN_MB = ONE_MB * 10
ONE_GB = ONE_MB * 1024

# Time constants
ONE_SECOND = 1
ONE_MINUTE = 60 * ONE_SECOND
ONE_HOUR = 60 * ONE_MINUTE
ONE_DAY = 24 * ONE_HOUR
ONE_WEEK = 7 * ONE_DAY
ONE_MONTH = 30 * ONE_DAY
ONE_YEAR = 365 * ONE_DAY

# Domain-specific constants
HSTS_MAX_AGE = ONE_YEAR
MAX_MESSAGE_SIZE = ONE_MB
MAX_ATTACHMENT_SIZE = ONE_GB
DEFAULT_CHUNK_SIZE = ONE_MB

# Resource Monitor constants
CPU_SAMPLE_INTERVAL = 0.1
TREND_SAMPLE_SIZE = 10
TREND_HISTORY_SIZE = 20
TREND_THRESHOLD = 5
CAPACITY_HIGH_THRESHOLD = 70
CAPACITY_MEDIUM_THRESHOLD = 50
DEFAULT_MONITOR_INTERVAL = 5.0
METRICS_HISTORY_MAX = 1000
ALERTS_MAX = 100
CPU_WARNING_THRESHOLD = 80.0
CPU_CRITICAL_THRESHOLD = 95.0
CPU_THRESHOLD_WARNING = 80
CPU_THRESHOLD_CRITICAL = 95
MEMORY_WARNING_THRESHOLD = 85.0
MEMORY_CRITICAL_THRESHOLD = 95.0
MEMORY_THRESHOLD_WARNING = 80
MEMORY_THRESHOLD_CRITICAL = 90
DISK_WARNING_THRESHOLD = 85.0
DISK_CRITICAL_THRESHOLD = 95.0
NETWORK_WARNING_THRESHOLD = 80.0
NETWORK_CRITICAL_THRESHOLD = 95.0
DEFAULT_METRICS_HISTORY_SECONDS = 60
DEFAULT_ALERT_COUNT = 10
DEFAULT_RECENT_ALERTS_COUNT = 5

# Memory Profiler constants
DEFAULT_SNAPSHOT_INTERVAL = 60.0
TOP_OBJECTS_COUNT = 20
SNAPSHOTS_MAX = 1000
HEAP_WARNING_PERCENT = 80.0
HEAP_CRITICAL_PERCENT = 90.0
GROWTH_RATE_WARNING = 10.0
GC_SPIKE_THRESHOLD = 2.0
MIN_SNAPSHOTS_FOR_LEAK = 5
RECENT_SNAPSHOTS_FOR_LEAK = 10
MIN_SNAPSHOTS_FOR_DETECTION = 3
LEAK_GROWTH_PERCENT_THRESHOLD = 50
LEAK_GROWTH_COUNT_THRESHOLD = 100
LEAK_SEVERITY_CRITICAL = 200
LEAK_SEVERITY_HIGH = 150
LEAK_SEVERITY_MEDIUM = 100
DRIFT_HEAP_THRESHOLD = 20
DRIFT_OBJECT_THRESHOLD = 30
DRIFT_GC_THRESHOLD = 10

# Scheduler constants
DEFAULT_STORAGE_GB = 10
RESOURCE_SCORE_WEIGHT = 0.4
LOAD_SCORE_PERCENTAGE_BASE = 100
LOAD_SCORE_WEIGHT = 0.15
LOCALITY_SCORE_DEFAULT = 0.3
SCHEDULER_QUEUE_TIMEOUT = 1.0
SCHEDULER_ERROR_SLEEP = 1
SCHEDULER_CHECK_INTERVAL = 1.0
SCHEDULER_CLEANUP_INTERVAL = 60
SCHEDULER_MAX_CONCURRENT_JOBS = 0

# Betanet constants
DEFAULT_PACKETS_PROCESSED = 22274
MOCK_NODE_PACKETS_1 = 12453
MOCK_NODE_PACKETS_2 = 9821
MOCK_NODE_UPTIME_1 = ONE_DAY
MOCK_NODE_UPTIME_2 = 72000
CONNECTIONS_PER_NODE = 3
DEFAULT_LATENCY_MS = 45.0
DEPLOYMENT_DELAY_SECONDS = 5
BETANET_CONNECTION_TIMEOUT = 5
BETANET_READ_TIMEOUT = 5
BETANET_MAX_RETRIES = 3
BETANET_BUFFER_SIZE = ONE_KB

# HTTP client timeout constants
HEALTH_CHECK_TIMEOUT = 2.0
SHORT_REQUEST_TIMEOUT = 5.0
LONG_REQUEST_TIMEOUT = 10.0

# Betanet route mock values
MOCK_BANDWIDTH = 1024
MOCK_THROUGHPUT = 850

# Deployment resource limits
MIN_CPU_CORES = 0.5
MAX_CPU_CORES = 16
MIN_MEMORY_MB = 512
MAX_MEMORY_MB = 16384
MIN_GPU_UNITS = 0
MAX_GPU_UNITS = 8
MIN_STORAGE_GB = 1
MAX_STORAGE_GB = 1000
DEFAULT_REPLICAS = 1
MIN_REPLICAS = 1
MAX_REPLICAS_INITIAL = 10
MAX_REPLICAS_SCALE = 100

# Cache TTL constants
DEPLOYMENT_STATUS_CACHE_TTL = 30
DEPLOYMENT_LIST_CACHE_TTL = 60
STATUS_HISTORY_LIMIT = 10

# Pagination defaults
DEFAULT_PAGE_LIMIT = 20
MAX_PAGE_LIMIT = 100
DEFAULT_OFFSET = 0

# Metrics aggregation constants
METRICS_BATCH_SIZE = 1000
METRICS_FLUSH_INTERVAL = ONE_MINUTE
