name: Rust Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build
      run: cargo build --verbose
      if: hashFiles('Cargo.toml') != ''

    - name: Run tests
      run: cargo test --verbose
      if: hashFiles('Cargo.toml') != ''

    - name: Run clippy
      run: cargo clippy -- -D warnings
      if: hashFiles('Cargo.toml') != ''
      continue-on-error: true